test

diff --git a/.github/workflows/actions-demo.yml b/.github/workflows/actions-demo.yml
--- a/.github/workflows/actions-demo.yml
+++ b/.github/workflows/actions-demo.yml
@@ -1,83 +1,34 @@
-name: Bump version
-on:
-  push:
-    branches:
-      - main
+name: Experiment
+on: [push]
+
 jobs:
-  store:
+  job1:
+    name: Job 1
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
-        with:
-           fetch-depth: '0'
-      - name: Bump version and push tag
-        id: tag_version
-        uses: anothrNick/github-tag-action@1.36.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          WITH_V: true
-          DRY_RUN: true
-      - name: Show new tag
-        run: |
-             echo " ${{ steps.tag_version.outputs.new_tag }}"
-    
-    
-  build:
-    runs-on: ubuntu-latest 
+    - name: Sleep and Run
+      run: |
+        echo "Sleeping for 10"
+        sleep 10
+
+  job2:
+    name: Job 2
+    needs: job1
+    runs-on: ubuntu-latest
+
     steps:
-       - uses: actions/checkout@v2
-       - name: Set up JDK 11 for x64
-         uses: actions/setup-java@v2
-         with:
-          java-version: '11'
-          distribution: adopt
-          architecture: x64
-         run: mvn clean install --batch-mode
-    
-  publish:
-      needs: build
-      runs-on: ubuntu-latest
-      permissions:
-        contents: read
-        packages: write
-      steps:
-        - uses: actions/checkout@v2
-        - uses: actions/setup-java@v2
-          with:
-            java-version: '11'
-            distribution: adopt
-        - name: Publish package
-          run: |
-            mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag
-            }}
-            mvn --batch-mode deploy
-          env:
-           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    
-  release:
-      needs: publish
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@main
-        - name: Create a Release
-      uses: elgohr/Github-Release-Action@main
-      env:
-        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
-      with:
-        args: ${{ steps.tag_version.outputs.new_tag }}        
-        
-  tag:
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v2
-          with:
-            fetch-depth: '0'
-        - name: Bump version and push tag
-          id: tag_version1
-          uses: anothrNick/github-tag-action@1.36.0
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            WITH_V: true
-        - name: Show new tag
-          run: |
-            echo " ${{ steps.tag_version1.outputs.new_tag }}"
+    - name: Dependant is Running
+      run: |
+        echo "Completed job 2, but triggering failure"
+        exit 1
+
+  job3:
+    name: Job 3
+    needs: job2
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Will never run
+      run: |
+        echo "If you can read this, the experiment failed"
